spring.application.name=url-shortner
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://url_shortner:xxx@urlshortner.s5fvbcu.mongodb.net/url_shortner?retryWrites=true&w=majority&appName=urlshortner}
